name: docker-images-build

on:
  push:
    branches: "*"
  schedule:
    - cron: "0 0 * * *"
 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jobqueue: ["pbs", "sge", "slurm"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check versions
        run: |
          docker version
          docker-compose version
      - name:  Building Image 
        shell: bash -l {0}
        run: |
          cd ./ci/${{ matrix.jobqueue }}
          docker-compose build 
      - name: List images
        run: |
          docker ps -a 
          docker images
          
      - name: Publish main images to DockerHub Registry
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: daskdev/dask-jobqueue:${{ matrix.jobqueue }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish secondary images to DockerHub Registry
        if: matrix.jobqueue == 'sge' && github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: daskdev/dask-jobqueue:${{ matrix.jobqueue }}-slave
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


          
      